version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: loan_app
      POSTGRES_USER: loan_app
      POSTGRES_PASSWORD: loan_app
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
