version: "3.7"

services:
  my_db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: loan_app
      POSTGRES_USER: loan_app
      POSTGRES_PASSWORD: loan_app

  loan_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: loan_app
      DB_PASSWORD: loan_app
    ports:
      - 8000:8000
    depends_on:
      - my_db

