# Generated by Django 3.1.12 on 2021-06-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Номер клиента')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(auto_now=True, verbose_name='Время подачи заявки')),
                ('product', models.CharField(choices=[('Одобрено', 'Approved'), ('Отказано', 'Denied'), ('Временный отказ', 'Temporary refusal')], max_length=15, verbose_name='На что кредит')),
                ('solution', models.CharField(blank=True, choices=[('Auto', 'Auto'), ('Потреб', 'Consumer'), ('Залог', 'Deposit'), ('Ипотека', 'Mortgage')], max_length=15, null=True, verbose_name='Решение по кредиту')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=250, verbose_name='Текст комментария')),
                ('loan_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.loanapplication')),
            ],
        ),
    ]
