# Generated by Django 3.1.12 on 2021-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='text_comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст комментария'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
