# Generated by Django 3.1.12 on 2021-06-06 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210605_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='date_application',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время подачи заявки'),
        ),
        migrations.CreateModel(
            name='StatusEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус поля')),
                ('loan_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
